# Base config
baseURL = "https://jankrl.github.io/ola-portfolio/"
theme = "LoveIt"
title = "Przykładowe portfolio dla Oli"

# Language config
languageCode = "pl"
languageName = "Polski"

# Site configuration
# https://hugoloveit.com/theme-documentation-basics/#site-configuration

[params]
  title = "Przykładowe portfolio dla Oli"
  [params.author]
    name = "Aleksandra"
  [params.header]
    subtitle = "Aleksandra"
    [params.header.title]
      name = "Przykładowe portfolio dla Oli"
  [params.home]
    [params.home.profile]
      subtitle = "Witaj na moim portfolio!"

# Menu
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posty"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tagi"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Kategorie"
    url = "/categories/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false